In [2]:
import numpy as np

In [3]:
matrix_1 = np.array([[2,3],[3,4]])
matrix_1

array([[2, 3],
       [3, 4]])

In [4]:
matrix_1.shape

(2, 2)

In [5]:
a = np.random.rand(3,4)

In [6]:
a

array([[0.54374297, 0.25009065, 0.10829396, 0.34316076],
       [0.8858657 , 0.60035394, 0.65216095, 0.70476716],
       [0.15408808, 0.87278898, 0.58972164, 0.19186345]])

In [8]:
b = np.random.randint(10,100,size=(3,3))

In [9]:
b

array([[65, 93, 32],
       [97, 35, 49],
       [93, 19, 49]])

In [13]:
b = np.ones((2,2))

In [14]:
b

array([[1., 1.],
       [1., 1.]])

In [16]:
b = b.reshape(-1,1)

In [17]:
b


array([[1.],
       [1.],
       [1.],
       [1.]])

In [20]:
identity_matrix = np.eye(8)

In [21]:
identity_matrix

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
a = np.random.randint(10,20,size=(3,3))

In [23]:
a.T

array([[11, 19, 16],
       [14, 17, 11],
       [14, 17, 16]])

In [24]:
a

array([[11, 14, 14],
       [19, 17, 17],
       [16, 11, 16]])

In [25]:
a

array([[11, 14, 14],
       [19, 17, 17],
       [16, 11, 16]])

In [26]:
a = a.T

In [27]:
a

array([[11, 19, 16],
       [14, 17, 11],
       [14, 17, 16]])